Refaktör

diff --git a/uech b/uech
--- a/uech
+++ b/uech
@@ -13,34 +13,24 @@ readonly PROGNAME=${0##*/}
 # Version
 readonly VERSION=0.0
 
-# Common functions for both sides (local and remote)
-anywhere() {
-	# UI helpers
-
+Ui() {
 	# Color palette
-	declare -Ag palette=(
-		[grey]="240"
-		[cyan]="14"
-		[red]="197"
-		[yellow]="11"
+	declare -Ag Palette=(
+		[grey]=240
+		[cyan]=14
+		[red]=197
+		[yellow]=11
 	)
 
+	palette.bold() {
+		echo -en "\e[1;38;5;${Palette[$1]}m"
+	}
+
+	palette.normal() {
+		echo -en "\e[38;5;${Palette[$1]}m"
+	}
+
 	palette.reset() {
-		local color
-		for color in "${!palette[@]}"; do
-			palette[$color]=
-		done
-	}
-
-	color.bold() {
-		echo -en "\e[1;38;5;${palette[$1]}m"
-	}
-
-	color.normal() {
-		echo -en "\e[38;5;${palette[$1]}m"
-	}
-
-	color.reset() {
 		echo -en "\e[0m"
 	}
 
@@ -63,46 +53,117 @@ anywhere() {
 		:
 	}
 
-	indent() {
-		sed 's/^/       /'
-	}
-
-	step.start() {
-		local step=$1
-		local color=$2
-		echo -e >&2 "$(color.bold "$color")-----> ${step}$(color.reset)$(color.normal "$color")"
-	}
-
-	step.failed() {
-		local step=$1
-		local err=$2
-		echo -e >&2 "$(color.bold "red")-----> ${step} step failed with exit code:$(color.reset) $err"
-	}
-
-	step.end() {
-		echo -e >&2 "$(color.reset)"
-	}
-
 	usage() {
 		cry "$PROGNAME [<flags>...] [<user>@]<host>[:<port>] <executable> [<arguments>...]"
 		cry "See $PROGNAME(1) for detailed information."
 		exit "${1:-0}"
 	}
 
-	# Self template
+	indent() {
+		sed 's/^/       /'
+	}
 
-	declare -ag args=() # command line arguments vector
+	nocr() {
+		sed "s/\r$//"
+	}
+
+	declare -Ag Color=(
+		[Local-]=yellow
+		[Upload]=grey
+		[Remote]=cyan
+		[Download]=grey
+		[Local+]=yellow
+	)
+
+	step.start() {
+		local step=$1
+		echo -e >&2 "$(palette.bold "${Color[$step]}")-----> ${step}$(palette.reset)$(palette.normal "${Color[$step]}")"
+	}
+
+	step.failed() {
+		local step=$1
+		local err=$2
+		echo -e >&2 "$(palette.bold "red")-----> ${step} step failed with exit code:$(palette.reset) $err"
+	}
+
+	step.stop() {
+		echo -e >&2 "$(palette.reset)"
+	}
+
+	declare -Ag Filter=(
+		[Local-]=filter.default
+		[Upload]=filter.default
+		[Remote]=filter.remote
+		[Download]=filter.default
+		[Local+]=filter.default
+	)
+
+	filter.default() {
+		indent
+	}
+
+	filter.remote() {
+		# Remove CR at the EOL which is generated by "ssh -t" and indent
+		nocr | indent
+	}
+
+	ui.do() {
+		local step=$1
+		shift
+
+		step.start "$step"
+
+		local err=
+
+		local filter=${Filter[$step]}
+		if [[ -n $filter ]]; then
+			{ "$@" 2>&1 1>&3 3>&- | "$filter"; } 3>&1 1>&2 | "$filter"
+		else
+			"$@"
+		fi || err=$?
+
+		[[ $err -eq 0 ]] || step.failed "$step" "$err"
+
+		step.stop
+
+		return $err
+	}
+
+	ui.nocolor() {
+		local c
+		for c in "${!Palette[@]}"; do
+			Palette[$c]=
+		done
+	}
+
+	ui.quiet() {
+		ui.do() {
+			shift
+			"$@"
+		}
+	}
+
+	ui.load() {
+		:
+	}
+
+	ui.load
+}
+
+# Self template for both sides (local and remote)
+Self() {
+	declare -ag Args=() # command line arguments vector
 
 	# Main template (all functions defined at the relevant side)
 	self.main() {
-		args=("$@")
+		Args=("$@")
 
 		self.flags
 		self.args
 
 		self.init
 
-		self.run "${args[@]}"
+		self.run "${Args[@]}"
 	}
 
 	# Initialize before run (overwritten by the current side)
@@ -115,9 +176,9 @@ anywhere() {
 		super.shutdown
 	}
 
-	# Enter the working directory (so called "center")
+	# Enter the working directory (so called the "center")
 	self.enter() {
-		pushd "${self[center]}" >/dev/null || die "Cannot chdir: '${self[center]}'"
+		pushd "${Self[center]}" >/dev/null || die "Cannot chdir: '${Self[center]}'"
 	}
 
 	# Leave the working directory
@@ -128,28 +189,31 @@ anywhere() {
 	# Dump self
 	self.debug() {
 		local key
-		for key in "${!self[@]}"; do
-			printf "%10s:  %s\n" "$key" "${self[$key]}"
+		for key in "${!Self[@]}"; do
+			printf "%10s:  %s\n" "$key" "${Self[$key]}"
 		done | indent >&2
 	}
 
 	# Base functions which should not be overwritten (hence super.)
 
-	declare -ag cleanup=()
+	declare -ag Cleanup=()
 
 	super.shutdown() {
-		rm -rf -- "${cleanup[@]}"
+		rm -rf -- "${Cleanup[@]}"
 	}
 
 	super.init() {
-		# Reset color palette
-		if [[ -n ${self[nocolor]} ]]; then
-			palette.reset
+		# Setup UI
+
+		if [[ -n ${Self[nocolor]} ]]; then
+			ui.nocolor
 		fi
 
-		# Setup conditional UI
+		if [[ -n ${Self[quiet]} ]]; then
+			ui.quiet
+		fi
 
-		if [[ -n ${self[debug]} ]]; then
+		if [[ -n ${Self[debug]} ]]; then
 			debug() {
 				echo -e >&2 "DEBUG: $*"
 			}
@@ -184,20 +248,21 @@ anywhere() {
 }
 
 # Functions for remote side
-there() {
+Remote() {
 	# Self object at the remote side
-	declare -Ag self=(
+	declare -Ag Self=(
 		[buffer]=""  # buffer directory
 		[debug]=""   # debug mode?
 		[exe]=""     # absolute path of the executable
 		[keep]=""    # keep remote store?
 		[local]=""   # local mode?
 		[nocolor]="" # no color?
+		[quiet]=""   # be quiet?
 	)
 
 	# Process options
 	self.flags() {
-		set -- "${args[@]}"
+		set -- "${Args[@]}"
 
 		local arg
 		while [[ $# -gt 0 ]]; do
@@ -205,16 +270,19 @@ there() {
 
 			case $arg in
 			-local)
-				self[local]=true
+				Self[local]=true
 				;;
 			-keep)
-				self[keep]=true
+				Self[keep]=true
 				;;
 			-nocolor)
-				self[nocolor]=true
+				Self[nocolor]=true
 				;;
 			-debug)
-				self[debug]=true
+				Self[debug]=true
+				;;
+			-quiet)
+				Self[quiet]=true
 				;;
 			-*)
 				bug "Unrecognized flag: $arg"
@@ -227,12 +295,12 @@ there() {
 			shift
 		done
 
-		args=("$@")
+		Args=("$@")
 	}
 
 	# Process (non-flag) arguments
 	self.args() {
-		set -- "${args[@]}"
+		set -- "${Args[@]}"
 
 		[[ $# -ge 1 ]] || bug "Missing arguments"
 
@@ -244,9 +312,9 @@ there() {
 		[[ $exe != /* ]] || bug "Must be a relative path: '$exe'"
 
 		# Convert the path of executable to an absolute path
-		self[exe]=$(readlink -f "$exe")
+		Self[exe]=$(readlink -f "$exe")
 
-		args=("$@")
+		Args=("$@")
 	}
 
 	# Post initialization after processing options and arguments
@@ -254,7 +322,7 @@ there() {
 		super.init
 
 		# Calculate center
-		self[center]=${self[exe]%/*}
+		Self[center]=${Self[exe]%/*}
 	}
 
 	# Shutdown procedure
@@ -264,13 +332,13 @@ there() {
 
 	# Run the executable
 	self.run() {
-		if [[ -n ${self[debug]} ]]; then
+		if [[ -n ${Self[debug]} ]]; then
 			debug "Remote"
 			self.debug
 		fi
 
 		self.enter
-		"${self[exe]}" REMOTE "$@"
+		"${Self[exe]}" REMOTE "$@"
 		self.leave
 	}
 
@@ -283,16 +351,16 @@ there() {
 		[[ -d $buffer ]] || bug "No buffer directory found: '$buffer'"
 		pushd "$buffer" >/dev/null || die "Cannot chdir to: '$buffer'"
 
-		self[buffer]=$buffer
+		Self[buffer]=$buffer
 	}
 
 	self.load
 }
 
 # Functions for local side
-here() {
+Local() {
 	# Self object at the local side
-	declare -Ag self=(
+	declare -Ag Self=(
 		[buffer]=""  # buffer directory
 		[center]=""  # absolute path of the working directory
 		[clean]=""   # clean remote store before?
@@ -305,14 +373,15 @@ here() {
 		[local]=""   # local mode?
 		[nocolor]="" # no color?
 		[noreuse]="" # no reuse ssh connection?
+		[quiet]=""   # be quiet?
 		[radius]=""  # radius from the working directory
 	)
 
-	declare -ag flags=() # flags to transfer to the remote side
+	declare -ag Flags=() # flags to transfer to the remote side
 
 	# Process options
 	self.flags() {
-		set -- "${args[@]}"
+		set -- "${Args[@]}"
 
 		local arg
 		while [[ $# -gt 0 ]]; do
@@ -333,10 +402,10 @@ here() {
 				[[ -n $value ]] || die "Argument required for flag: '-radius'"
 				[[ $value =~ [0-9]+ ]] || die "Radius must be an integer: '$value'"
 
-				self[radius]=$value
+				Self[radius]=$value
 				;;
 			-git)
-				self[git]=true
+				Self[git]=true
 				;;
 			-buffer|-buffer=*)
 				local value
@@ -351,11 +420,11 @@ here() {
 				esac
 				[[ -n $value ]] || die "Argument required for flag: '-buffer'"
 
-				self[buffer]=$value
+				Self[buffer]=$value
 				;;
 			-keep)
-				self[keep]=true
-				flags+=("$arg")
+				Self[keep]=true
+				Flags+=("$arg")
 				;;
 			-config|-config=*)
 				local value
@@ -371,25 +440,29 @@ here() {
 				[[ -n $value ]] || die "Argument required for flag: '-config'"
 				[[ -f $value ]] || die "No such file: '$value'"
 
-				self[config]=$(readlink -f "$value")
+				Self[config]=$(readlink -f "$value")
 				;;
 			-local)
-				self[local]=true
-				flags+=("$arg")
+				Self[local]=true
+				Flags+=("$arg")
 				;;
 			-clean)
-				self[clean]=true
+				Self[clean]=true
 				;;
 			-nocolor)
-				self[nocolor]=true
-				flags+=("$arg")
+				Self[nocolor]=true
+				Flags+=("$arg")
 				;;
 			-noreuse)
-				self[noreuse]=true
+				Self[noreuse]=true
 				;;
 			-debug)
-				self[debug]=true
-				flags+=("$arg")
+				Self[debug]=true
+				Flags+=("$arg")
+				;;
+			-quiet)
+				Self[quiet]=true
+				Flags+=("$arg")
 				;;
 			-version)
 				echo "$VERSION"
@@ -409,12 +482,12 @@ here() {
 			shift
 		done
 
-		args=("$@")
+		Args=("$@")
 	}
 
 	# Process (non-flag) arguments
 	self.args() {
-		set -- "${args[@]}"
+		set -- "${Args[@]}"
 
 		[[ $# -ge 2 ]] || usage 2
 
@@ -426,7 +499,7 @@ here() {
 		# Catch bogus hostname (e.g. file path as hostname)
 		[[ ! $host =~ [/\\] ]] || die "Invalid host name"
 
-		self[host]=$host
+		Self[host]=$host
 
 		local exe=$1
 		shift
@@ -435,17 +508,17 @@ here() {
 		[[ -x $exe ]] || die "Not an executable: '$exe'"
 
 		# Convert the path of executable to an absolute path
-		self[exe]=$(readlink -f "$exe")
+		Self[exe]=$(readlink -f "$exe")
 
-		args=("$@")
+		Args=("$@")
 	}
 
 	# Create buffer beforehand
 	self.buffer() {
-		local buffer=${self[buffer]}
+		local buffer=${Self[buffer]}
 
 		if [[ -z $buffer ]]; then
-			if [[ -z ${self[local]} ]]; then
+			if [[ -z ${Self[local]} ]]; then
 				buffer=$(
 					ssh.run /bin/mktemp -d -t uech.XXXXXX
 				)
@@ -453,9 +526,9 @@ here() {
 				buffer=$(/bin/mktemp -d -t uech.XXXXXX)
 			fi
 		else
-			if [[ -z ${self[local]} ]]; then
+			if [[ -z ${Self[local]} ]]; then
 				buffer=$(
-					ssh.run bash -e -s "$buffer" "${self[clean]}" <<-'EOF'
+					ssh.run bash -e -s "$buffer" "${Self[clean]}" <<-'EOF'
 						[[ -z "$2" ]] || rm -rf "${1:?}"
 						mkdir -m 700 -p "$1"
 						cd "$1"
@@ -464,7 +537,7 @@ here() {
 				)
 			else
 				[[ $buffer = /* ]] || buffer="$HOME/$buffer"
-				[[ -z "${self[clean]}" ]] || rm -rf "${buffer:?}"
+				[[ -z "${Self[clean]}" ]] || rm -rf "${buffer:?}"
 				# shellcheck disable=2174
 				mkdir -m 700 -p "$buffer"
 			fi
@@ -473,7 +546,7 @@ here() {
 
 		debug "Buffer successfully created: $buffer"
 
-		self[buffer]=$buffer
+		Self[buffer]=$buffer
 	}
 
 	# Setup flags affected from the presence of a Git repository
@@ -483,16 +556,16 @@ here() {
 		local gitdir
 		if gitdir=$(git rev-parse --show-toplevel 2>/dev/null); then
 			# Sanity check
-			if git check-ignore -q --no-index "${self[exe]}"; then
+			if git check-ignore -q --no-index "${Self[exe]}"; then
 				cry "Executable must be tracked, otherwise it won't be copied to remote."
-				die "Git ignored executable: '${self[exe]}'"
+				die "Git ignored executable: '${Self[exe]}'"
 			fi
 			# Set radius to the repository depth
-			if [[ -z ${self[radius]} ]]; then
-				self[radius]=$(radius "${self[center]}" "$gitdir")
+			if [[ -z ${Self[radius]} ]]; then
+				Self[radius]=$(radius "${Self[center]}" "$gitdir")
 			fi
 		else
-			self[git]=
+			Self[git]=
 		fi
 
 		self.leave
@@ -503,17 +576,17 @@ here() {
 		super.init
 
 		# Calculate center
-		self[center]=${self[exe]%/*}
+		Self[center]=${Self[exe]%/*}
 
-		if [[ -n ${self[clean]} ]] && [[ -z ${self[buffer]} ]]; then
+		if [[ -n ${Self[clean]} ]] && [[ -z ${Self[buffer]} ]]; then
 			die "Flag '-clean' must be used with '-buffer' flag"
 		fi
 
-		[[ -z ${self[git]} ]] || self.gitflag
+		[[ -z ${Self[git]} ]] || self.gitflag
 
-		[[ -n ${self[radius]} ]] || self[radius]=0
+		[[ -n ${Self[radius]} ]] || Self[radius]=0
 
-		if [[ -z ${self[local]} ]]; then
+		if [[ -z ${Self[local]} ]]; then
 			ssh.init
 		fi
 
@@ -522,15 +595,15 @@ here() {
 
 	# Shutdown before exit
 	self.shutdown() {
-		if [[ -z ${self[keep]} ]]; then
-			if [[ -z ${self[local]} ]]; then
-				ssh.run rm -rf "${self[buffer]}"
+		if [[ -z ${Self[keep]} ]]; then
+			if [[ -z ${Self[local]} ]]; then
+				ssh.run rm -rf "${Self[buffer]}"
 			else
-				rm -rf -- "${self[buffer]}"
+				rm -rf -- "${Self[buffer]}"
 			fi
 		fi
 
-		if [[ -z ${self[local]} ]] && [[ -z ${self[noreuse]} ]]; then
+		if [[ -z ${Self[local]} ]] && [[ -z ${Self[noreuse]} ]]; then
 			ssh.shutdown
 		fi
 
@@ -543,27 +616,25 @@ here() {
 
 		local -a env=(
 			# An indicator that we are on the remote side
-			"UECH_REMOTE=${self[buffer]}"
+			"UECH_REMOTE=${Self[buffer]}"
 		)
 
 		local periphery
-		periphery=$(periphery "${self[radius]}")
+		periphery=$(periphery "${Self[radius]}")
 
 		# Convert executable path to a relative path
 		local exe
-		exe=$(realpath --relative-to="${periphery:-.}" "${self[exe]}")
+		exe=$(realpath --relative-to="${periphery:-.}" "${Self[exe]}")
 
 		local err=
 
-		if [[ -z ${self[local]} ]]; then
+		if [[ -z ${Self[local]} ]]; then
 			local progfile
 			progfile=$(ssh.run /bin/mktemp -t uech.XXXXXX) || die "mktemp error"
 
 			ssh.run "cat >'$progfile'" <"$PROGFILE" || err=$?
 			if [[ $err -eq 0 ]]; then
-				ssh.run_with_tty env "${env[@]}" bash "$progfile" "${flags[@]}" "$exe" "$@" |
-				# Remove CR at the end of the line which is generated by "ssh -t"
-				sed "s/\r$//" || err=$?
+				ssh.run_with_tty env "${env[@]}" bash "$progfile" "${Flags[@]}" "$exe" "$@"  || err=$?
 			else
 				cry "Couldn't copy itself"
 			fi
@@ -571,7 +642,7 @@ here() {
 			ssh.run rm -f -- "$progfile" || true
 		else
 			env "${env[@]}" \
-				bash -s	-- "${flags[@]}" "$exe" "$@" <"$PROGFILE"
+				bash -s	-- "${Flags[@]}" "$exe" "$@" <"$PROGFILE"
 		fi
 
 		self.leave
@@ -585,14 +656,14 @@ here() {
 		local dest
 
 		local periphery
-		periphery=$(periphery "${self[radius]}")
+		periphery=$(periphery "${Self[radius]}")
 
-		src=${periphery:-${self[exe]}}
+		src=${periphery:-${Self[exe]}}
 
-		if [[ -z ${self[local]} ]]; then
-			dest=${self[host]}:${self[buffer]}
+		if [[ -z ${Self[local]} ]]; then
+			dest=${Self[host]}:${Self[buffer]}
 		else
-			dest=${self[buffer]}
+			dest=${Self[buffer]}
 		fi
 
 		rsync.run "$src" "$dest"
@@ -604,14 +675,14 @@ here() {
 		local dest
 
 		# XXX: Watch for the trailing slash
-		if [[ -z ${self[local]} ]]; then
-			src=${self[host]}:${self[buffer]}/
+		if [[ -z ${Self[local]} ]]; then
+			src=${Self[host]}:${Self[buffer]}/
 		else
-			src=${self[buffer]}/
+			src=${Self[buffer]}/
 		fi
 
 		local periphery
-		periphery=$(periphery "${self[radius]}")
+		periphery=$(periphery "${Self[radius]}")
 
 		dest=${periphery:-.}
 
@@ -620,66 +691,38 @@ here() {
 
 	# Run the executable
 	self.run() {
-		if [[ -n ${self[debug]} ]]; then
+		if [[ -n ${Self[debug]} ]]; then
 			debug "Local"
 			self.debug
 		fi
 
-		self.do "Local-" "yellow" "${self[exe]}" LOCAL- "$@"
-
-		self.do "Upload" "grey" self.upload
-
-		self.do "Remote" "cyan" self.remote "$@"
-
-		# If radius is zero, there is nothing at the remote side which needs to be downloaded
-		if [[ ${self[radius]} -gt 0 ]]; then
-			self.do "Download" "grey" self.download
-		fi
-
-		self.do "Local+" "yellow" "${self[exe]}" LOCAL+ "$@"
-	}
-
-	# Do the given action at the center
-	self.do() {
-		local step=$1
-		shift
-
-		local color=$1
-		shift
-
-		local err=
-
 		self.enter
 
-		step.start "$step" "$color"
-		{ "$@" 2>&1 1>&3 3>&- | indent; } 3>&1 1>&2 | indent || err=$?
-		if [[ $err -ne 0 ]]; then
-			step.failed "$step" "$err"
-		fi
-		step.end
+		ui.do Local- "${Self[exe]}" LOCAL- "$@"
+		ui.do Upload self.upload
+		ui.do Remote self.remote "$@"
+		[[ ${Self[radius]} -eq 0 ]] || ui.do Download self.download # for radius zero, nothing to download
+		ui.do Local+ "${Self[exe]}" LOCAL+ "$@"
 
 		self.leave
-
-		return $err
 	}
-
 
 	# Wrap ssh
 
-	declare -ag ssh=() # argument vector which will be passed to SSH
+	declare -ag Ssh=() # argument vector which will be passed to SSH
 
 	# Build SSH flags
 	ssh.init() {
 		super.init
 
-		if [[ -n ${self[config]} ]]; then
-			ssh+=(
+		if [[ -n ${Self[config]} ]]; then
+			Ssh+=(
 				"-F"
-				"${self[config]}"
+				"${Self[config]}"
 			)
 		fi
 
-		local host=${self[host]}
+		local host=${Self[host]}
 
 		# Check if we have a composite hostname, e.g. user@host:port
 
@@ -694,7 +737,7 @@ here() {
 					die "Malformed user specification: '$host'"
 				fi
 
-				ssh+=(
+				Ssh+=(
 					"-l"
 					"$user"
 				)
@@ -708,16 +751,16 @@ here() {
 					die "Malformed port specification: '$host'"
 				fi
 
-				ssh+=(
+				Ssh+=(
 					"-p"
 					"$port"
 				)
 			fi
 
-			self[host]=$name
+			Self[host]=$name
 		fi
 
-		[[ -n ${self[noreuse]} ]] || ssh.reuse
+		[[ -n ${Self[noreuse]} ]] || ssh.reuse
 	}
 
 	# Setup SSH to reuse connection
@@ -725,42 +768,42 @@ here() {
 		local tempdir
 
 		tempdir=$(/bin/mktemp -d -t ssh.XXXXXX) || die "Error creating a temp directory"
-		cleanup+=("$tempdir")
+		Cleanup+=("$tempdir")
 
 		debug "Initiating SSH"
 
 		local ctrlpath="$tempdir/%r@%h:%p"
 
 		# shellcheck disable=SC2029
-		ssh "${ssh[@]}" -n -N -f -o ControlMaster=yes -o ControlPath="$ctrlpath" "${self[host]}"
+		ssh "${Ssh[@]}" -n -N -f -o ControlMaster=yes -o ControlPath="$ctrlpath" "${Self[host]}"
 
-		ssh+=(
+		Ssh+=(
 			"-o"
 			"ControlPath=$ctrlpath"
 		)
 
 		# shellcheck disable=SC2029
-		ssh "${ssh[@]}" -q -O check "${self[host]}" 2>/dev/null || die "SSH master check failed"
+		ssh "${Ssh[@]}" -q -O check "${Self[host]}" 2>/dev/null || die "SSH master check failed"
 	}
 
 	# Invoke SSH with the ssh flags and host
 	ssh.run() {
-		debug "Invoking ssh:" "${ssh[@]}" "${self[host]}" "$@"
+		debug "Invoking ssh:" "${Ssh[@]}" "${Self[host]}" "$@"
 		# shellcheck disable=SC2029
-		ssh "${ssh[@]}" "${self[host]}" "$@"
+		ssh "${Ssh[@]}" "${Self[host]}" "$@"
 	}
 
 	# Invoke SSH with pseudo-terminal allocation
 	ssh.run_with_tty() {
-		debug "Invoking ssh:" -t "${ssh[@]}" "${self[host]}" "$@"
+		debug "Invoking ssh:" -t "${Ssh[@]}" "${Self[host]}" "$@"
 		# shellcheck disable=SC2029
-		ssh -t -o LogLevel=QUIET "${ssh[@]}" "${self[host]}" "$@"
+		ssh -t -o LogLevel=QUIET "${Ssh[@]}" "${Self[host]}" "$@"
 	}
 
 	# Shutdown SSH connection
 	ssh.shutdown() {
 		# shellcheck disable=SC2029
-		ssh "${ssh[@]}" -q -O exit "${self[host]}"
+		ssh "${Ssh[@]}" -q -O exit "${Self[host]}"
 	}
 
 	# Wrap rsync
@@ -771,22 +814,26 @@ here() {
 			"-a" # archive mode
 			"-z" # compress
 		)
-		if [[ -n ${self[git]} ]]; then
+		if [[ -n ${Self[git]} ]]; then
 			flags+=(
 				"-C"                 # ignore .git
 				"-f" ":- .gitignore" # ignore gitignored files
 			)
 		fi
 
-		[[ -z ${self[debug]} ]] || flags+=(
+		[[ -z ${Self[debug]} ]] || flags+=(
 			"-v"
 			"-P"
 		)
 
-		if [[ ${#ssh[@]} -gt 0 ]]; then
+		[[ -z ${Self[quiet]} ]] || flags+=(
+			"-q"
+		)
+
+		if [[ ${#Ssh[@]} -gt 0 ]]; then
 			flags+=(
 				"-e"
-				"ssh $(join ' ' "${ssh[@]}")"
+				"ssh $(join ' ' "${Ssh[@]}")"
 			)
 		fi
 
@@ -849,19 +896,19 @@ here() {
 	self.load
 }
 
-# Load the modules
-load() {
-	anywhere
-	if [[ -z ${UECH_REMOTE:-} ]]; then
-		here
-	else
-		there
-	fi
-}
-
-# Main invocation
+# Main entry
 main() {
-	load
+	# Load the modules
+	Ui
+
+	Self
+	if [[ -z ${UECH_REMOTE:-} ]]; then
+		Local
+	else
+		Remote
+	fi
+
+	# Invoke
 	self.main "$@"
 }
 
